/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "inverse-primary": "#c3c0ff",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-container-high": "#e6e8ea",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f4f6",
        "outline-variant": "#c7c4d8",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#dae2fd",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#0f0069",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#131b2e",
        "primary-fixed": "#e2dfff",
        "surface-container": "#eceef0",
        "on-error": "#ffffff",
        "outline": "#777587",
        "on-background": "#191c1e",
        "primary-fixed-dim": "#c3c0ff",
        "surface-bright": "#f7f9fb",
        "tertiary": "#3130c0",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#dad7ff",
        "secondary-container": "#dae2fd",
        "secondary": "#565e74",
        "on-tertiary-fixed": "#07006c",
        "on-tertiary-container": "#d9d8ff",
        "on-primary-fixed-variant": "#3323cc",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "primary-container": "#4f46e5",
        "surface": "#f7f9fb",
        "background": "#f7f9fb",
        "primary": "#3525cd",
        "on-secondary-container": "#5c647a",
        "surface-variant": "#e0e3e5",
        "tertiary-container": "#4b4dd8",
        "surface-tint": "#4d44e3",
        "tertiary-fixed": "#e1e0ff",
        "surface-dim": "#d8dadc",
        "on-surface-variant": "#464555",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "32px",
        "xs": "8px",
        "lg": "24px",
        "base": "4px",
        "sidebar-width": "260px",
        "sm": "12px",
        "md": "16px",
        "container-max": "1440px"
      },
      fontFamily: {
        "headline-md": ["Manrope", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}

